### ISSUE TITLE
pre-train weights

### ISSUE THREAD

**Issue by AlanNewImage** [mumianyuxin/M3DSSD#2]
Will release the pre-trained model in the future?

**Comment by mumianyuxin** [comment]
Thanks for your interest in our work. We have no plans to release the pre-trained model in the short term.

**Comment by Dinghow** [comment]
> Thanks for your interest in our work. We have no plans to release the pre-trained model in the short term.

Hi, mumianyuxin, I can not reproduce your performance based on your code & config,  there is a great gap, could you please share your pre-trained weight? thx a lot.
