### ISSUE TITLE
Training is not working

### ISSUE THREAD

**Issue by kdheejb7** [mumianyuxin/M3DSSD#4]
Hello, 
I tried to build and train your code, M3DSSD.
But I have one problem with training.

I ran the following command with the guide you provided.
`python3 scripts/train_rpn_3d.py --config=kitti_3d_base --exp_name base`

But I got the following error.

```Traceback (most recent call last):
  File "scripts/train_rpn_3d.py", line 324, in <module>
    main(args)
  File "scripts/train_rpn_3d.py", line 114, in main
    dataset = Kitti_Dataset_torch(conf, paths)
  File "/workspace/lib/dataloader.py", line 892, in __init__
    generate_anchors(conf, self.imdb, paths.data_cache) # generate anchors to conf.anchors
  File "/workspace/lib/rpn_util.py", line 118, in generate_anchors
    ols = iou(anchors[:, 0:4], normalized_gts[:, 0:4])
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

I checked that normalized_gts.shape is (0,), so I think there is no loaded data in normalized_gts.
Then I took a look at the rpn_util.py, dataloader.py, and train_rpn_3d.py.
I found out that normalized_gts was from "imdb", and "imdb" was from train_imdb.pkl" file.

But I don't have the train_imdb.pkl file, so any data cannot be loaded to imdb and normalized_gts.

How can I get the pkl file and solve this problem? 

Thank you!

**Comment by kdheejb7** [comment]
Sorry, this is my wrong path of dataset!
This problem was because I confused my kitti data's datapath :( 

I closed the issue! Thanks!

**Comment by alfinnurhalim** [comment]
how did you solve this problem?
